version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    filters:
      branches:
        only:
        - master
    steps:
      - checkout
      - run:
          name: Deploying to github pages
          command: |
            git config --global user.email "bh4aws@163.com"
            git config --global user.name "bh4aws@163.com"
            echo "machine github.com login bh4aws@163.com password $GITHUB_TOKEN" > ~/.netrc
            npm install && GIT_USER=bh4aws@163.com npm run deploy
workflows:
  sample:
    jobs:
      - build-and-test
